create table public.stock_watchlist (
  id bigint generated by default as identity primary key,
  ticker text not null unique,
  company_name text not null,
  sector text not null,
  watch_status text not null,
  target_price numeric(10, 2) not null check (target_price > 0),
  created_at timestamptz not null default now()
);

alter table public.stock_watchlist enable row level security;

grant select on table public.stock_watchlist to anon;
revoke insert, update, delete, truncate, references, trigger
on table public.stock_watchlist from anon;

create policy "Public can read stock watchlist"
on public.stock_watchlist
for select
to anon
using (true);

insert into public.stock_watchlist
  (ticker, company_name, sector, watch_status, target_price)
values
  ('AAPL', 'Apple', 'Technology', 'Core holding', 285.00),
  ('MSFT', 'Microsoft', 'Technology', 'Watching', 575.00),
  ('NVDA', 'NVIDIA', 'Semiconductors', 'High conviction', 235.00),
  ('TSLA', 'Tesla', 'Automotive', 'On watch', 525.00);
